import { readdirSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const localesDir = join(root, "locales");
const outFile = join(root, "src", "lib", "i18n-data.js");

const files = readdirSync(localesDir).filter(name => name.endsWith(".json")).sort();
if (!files.includes("en.json")) {
  console.error("locales/en.json is required");
  process.exit(1);
}

const en = JSON.parse(readFileSync(join(localesDir, "en.json"), "utf8"));
const enKeys = Object.keys(en);
const data = {};

const placeholders = text => (text.match(/\{[a-z_0-9]+\}/gi) || []).sort().join(",");

// JSON.parse silently keeps the last of a repeated key.
function duplicateKeys(source) {
  const seen = new Set();
  const repeated = [];
  for (const line of source.split("\n")) {
    const match = line.match(/^ {2}"([^"]+)":/);
    if (!match) continue;
    if (seen.has(match[1])) repeated.push(match[1]);
    else seen.add(match[1]);
  }
  return repeated;
}

let broken = 0;

for (const file of files) {
  const code = file.slice(0, -".json".length);
  const source = readFileSync(join(localesDir, file), "utf8");
  const catalog = JSON.parse(source);

  const repeated = duplicateKeys(source);
  if (repeated.length) {
    console.error(`${code}: ${repeated.length} duplicate key(s), earlier translation discarded: ${repeated.join(", ")}`);
    broken++;
  }

  if (code !== "en") {
    const missing = enKeys.filter(key => catalog[key] == null);
    if (missing.length) {
      console.warn(`${code}: ${missing.length} keys falling back to English`);
      for (const key of missing) catalog[key] = en[key];
    }
    for (const key of enKeys) {
      if (placeholders(en[key]) !== placeholders(catalog[key])) {
        console.error(`${code}: ${key} expects ${placeholders(en[key]) || "no placeholders"}, has ${placeholders(catalog[key]) || "none"}`);
        broken++;
      }
      const lost = (side) => side.test(en[key]) && !side.test(catalog[key]);
      if (lost(/^\s/) || lost(/\s$/)) {
        console.error(`${code}: ${key} drops the leading or trailing space the English relies on`);
        broken++;
      }
    }
  }
  data[code] = catalog;
}

if (broken) process.exit(1);

mkdirSync(dirname(outFile), { recursive: true });
const body = `// Generated by scripts/compile-i18n.mjs — do not edit.\n`
  + `export default ${JSON.stringify(data)};\n`;
writeFileSync(outFile, body);
console.log(`i18n: ${files.length} locales, ${enKeys.length} keys → src/lib/i18n-data.js`);
